# Discussion

In the analysis of water temperature, the results suggest that water temperatures will almost certainly exceed 85°F in the next five years. And this won't just happen once, but multiple times. The most concerning months are June, July, and August, which are projected to be above this threshold with *extremely* high probabilities every year. The month of September presents a more complicated case. It is projected to be above the water temperature threshold in 2027 and 2028, but with a greater uncertainty than the previously mentioned months. In 2029, September has a near certain probability (0.99) to be above the threshold. This suggests that while September may remain below the threshold in the short term, it will likely be a problem beyond the five-year mark.

Since it seems high water temperatures will certainly be an issue, the secondary analysis becomes all the more critical. Unlike water temperature, energy demand over the months shows a less predictable trend, as we found an adjusted R-squared value of 0.66. Regardless, it’s still worthwhile to check the energy demand trends in the model due to the dire situation. Unfortunately, the findings offer little reassurance. The months that were identified as worrisome in the primary analysis correspond to a spike in energy demand. Specifically, July and August have the *highest* predicted demand out of all months with demands of 776,457 MWh and 788,363 MWh, respectively. With a power plant working at reduced capacity, that is not exactly the comforting information needed

One limitation of this analysis is that the energy demand model was only based on data from the past year. A more precise model would incorporate multiple years worth of data. There is surely some variation from year to year on which months see the highest energy demand and at what level that is. That being said, the energy industry hasn’t changed drastically in recent years, so these results should still be heavily considered. Another limitation of this analysis is that the water temperature model didn’t consider any additional factors that influence water temperature apart from time of year. There are certainly more factors, such as greenhouse gas emissions, but time of year is likely the most influential and was therefore the primary focus.

Although these results present challenges for the power plant, they aren’t entirely surprising. Climate change has had a significant impact on temperature patterns and, as a result, the power plant’s operations. This analysis simply identified the hottest months of the year, so it's reasonable that the water temperature in those months will continue to rise assuming no impactful changes. Given these projections, it is vital that the Dauphin Island Power Plant starts to prepare for its future under these conditions. One future avenue of research that needs to be considered is exploring ways to raise the water temperature threshold at which reduced operating capacity occurs. In the meantime, short term solutions will be necessary to bridge the gap to long-term solutions. Starting preparation now is essential to maintaining reliable energy production in the coming years.
