---
title: "Draft: Intro/Conclusions"
---

## Introduction {.unnumbered}

Climate change is becoming an increasingly impactful phenomenon around the globe. For businesses, evaluating long-term sustainability with rising temperatures is becoming more and more essential. Specifically, The Dauphin Island Power Plan, located off the coast in Alabama, needs to consider changing water temperatures and how they will impact energy production. In response to a request from one of the plant’s managers, I conducted an analysis on water temperature in the next five years and the potential impact on operations.

When the plant was built in 1970, it relied on the assumption that water temperatures would stay below 85°F most days of the year. In our current climate, that assumption might be a bit far fetched, but back then it was quite reasonable. The unfortunate consequence of this assumption is that when the water temperature goes above the threshold, the power plant must operate at reduced capacity to stay within regulations. This limitation has started to raise serious concerns about reliability in the past decade, especially as energy demand increases.

The question that naturally arises is how likely are water temperatures to exceed 85°F in the Dauphin Island area and, if likely, when are the months to prepare for. In the subsequent analysis, I answer this question using a Standard Linear Model to project future water temperatures based on historical data. To fully understand the operational risk and impact, I also examined the energy demand around times of projected high water temperatures using a second Standard Linear Model. This provides a more complete picture of how reduced capacity could align with energy demand.

The goal of this analysis is to help the Dauphin Island Power Plant anticipate future challenges and begin planning for mitigation. This report provides the data-driven foundation to take proactive steps, whatever those may be.

## Discussion {.unnumbered}

In the first analysis of water temperature, the results suggest that water temperatures will almost certainly exceed 85°F in the next five years. The most concerning months are June, July, and August, which are projected to be above this threshold with extremely high probabilities every year. The month of September presents a more complicated case. It is projected to be above the water temperature threshold in 2027 and 2028, both with more uncertainty. In 2029, it has a near certain probability (0.99) to be above the threshold. This suggests that while September may remain below the threshold in the short term, it will likely be a problem beyond the five-year mark.

Since it seems high water temperatures will certainly be an issue, the secondary analysis becomes all the more critical. Unlike water temperature, energy demand over the months shows a less predictable trend, with an Adjusted R-squared value of 0.66. Regardless, it’s still worthwhile to check the trends of energy demand in our current model due to the dire situation. Spoiler alert, the findings offer little reassurance. The months that we identified to have the highest water temperatures correspond to a spike in energy demand. Specifically, July and August have the highest predicted demand out of all months with demands of 776,457 MWh and 788,363 Mwh, respectively. With a power plant working at reduced capacity, that is not exactly comforting information.

One limitation of this analysis is that the energy demand model was only based on data from the past year. Surely there is some variation from year to year on which months see the highest energy demand and at what level that is. That being said, the energy industry hasn’t changed drastically in recent years, so these results should still be heavily considered. Another limitation of this analysis is that the water temperature model didn’t consider any factors that influence water temperature, except for time of year. There are certainly more factors, such as greenhouse gas emissions, but time of year is likely the most influential and was therefore the primary focus.

Although these results present challenges for the power plant, they aren’t entirely surprising. Climate change has had a significant impact on temperature patterns and, as a result, our power plant’s operations. The hottest months of the year are the ones that this analysis identified, so it only makes sense that the water temperature in those months will continue to rise assuming no impactful changes. Given these projections, it is important that we start to prepare for the future of this power plant under these conditions. One future avenue of research that we need to consider is exploring ways to raise the water temperature threshold at which reduced operating capacity occurs. Is this a viable and timely solution in the given timeframe? In the meantime, short term solutions will be necessary to bridge the gap to long-term solutions. Starting our preparation now is essential to maintaining solid energy production in the coming years.
