---
title: "Draft: Executive Summary"
---

With climate change on the rise, the Dauphin Island Power Plant must consider how increasing water temperatures will impact its operations. Currently, the plant relies on the assumption that water temperatures will remain below 85°F. When temperatures exceed this threshold, the power plant must operate at reduced capacity, limiting its ability to meet energy demands. Analyzing water temperatures and calculating the likelihood that they exceed the 85°F threshold in the future is critical to mitigating risks. Additionally, examining how periods of high water temperature correspond to peaks in energy demand will help us better evaluate the impact of reduced capacity.

Our water temperature analysis generated projections for the next five years around the plant’s location. Eighteen months over the next five years are predicted to have water temperatures exceeding the threshold, almost all with a probability approaching 100%. The months that are projected to repeatedly exceed 85°F are June, July, August, and September.

In our secondary analysis of energy demand, we examined the months of the year to find when energy demand peaked. Alarmingly, there was a huge spike in energy demand in the months that we identified would exceed the water temperature threshold. Specifically, July and August have the highest energy demand out of the whole year.

These findings raise substantial concerns for the Dauphin Island Power Plant. One-third of each upcoming year is almost guaranteed to have water temperatures exceeding the threshold. As a result, the plant will be operating at reduced capacity for a third of each year in the near future. Unfortunately, periods of high water temperatures align with times of high energy demand. This makes the impact of reduced capacity much more significant. 

While these results are troubling, they are not surprising as climate change has greatly impacted sustainability across most industries. The hottest months of the year were identified in our analysis, which only makes sense that they correspond to the highest water temperatures. We need to immediately explore different solutions to combat these rising temperatures, such as raising the temperature threshold at which reduced operating capacity kicks in. Starting our preparation now is essential to maintaining reliable energy production in the coming years.





