# Methods

## Water Temperature Data

The water temperature data was obtained from the National Data Buoy Center (NDBC), specifically using a buoy located off the eastern coast of Dauphin Island. This buoy collects data at regular intervals, generally 30-minutes long, but certain months were had 6-minute intervals. To standardize the data for analysis, we only retained measurements taken at the top of each hour (3:00, 4:00, 5:00, etc.). The time period of this data spanned from January 1, 2022 to December 31, 2024.

In addition to removing unnecessary data points, many features of the dataset were irrelevant. Only three features were retained for the analysis: Year, Month, and Water Temperature. The independent variables were Year and Month, while the dependent variable in our analysis was Water Temperature. Originally measured in degrees Celsius, the water temperature data was converted to degrees Fahrenheit to align with the operational threshold relevant to the research question.

## Energy Data

The energy data was collected by Southern Company, the largest energy utility company in the Southeastern United States, but sourced from the U.S. Energy Administration (EIA). The EIA verified and cleaned up Southern Company's original data, and subsequently made it available to the public. The time period for this data spans from March 1, 2024 to February 27, 2025, with measurements taken once per day. Originally, we intended to analyze more than a year's worth of data, but we were constrained to what the EIA had available.

Similar to the water temperature dataset, unnecessary features were removed from this dataset, keeping only the Timestamp and Energy Demand. The Timestamp feature was later separated into individual time components, but only the Month feature was kept to identify monthly demand patterns. Since we only had data for a single year, the Year feature provided no additional insight. The other important feature, Energy Demand, was the dependent variable. For the purposes of our analysis, Demand is defined as the amount of electricity load within Southern Company's electric system, measured in megawatt-hours (MWh).

## Statistical Analyses

All statistical analyses were performed using R version 4.3.1 and the tidyverse package version 2.0.0. We first performed a simple Exploratory Data Analysis (EDA), visualizing trends and using base R functions such as `summary()`, `sd()`, `max()`, and `min()` to establish baseline statistics.

Following this phase, both the water temperature data and energy data were fitted on Standard Linear Models. For the water model, our goal was to project future water temperatures and their probabilities. On the contrary, for the energy model we were primarily interested in the significance of the overall F statistic. If this was significant, examining monthly averages would give solid insight into periods with high energy demand.
